SchoolShudale/Controllers/ConsultationController.cs
using BookFindingAndRatingSystem.Data.Models;
using Library.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Schedule.Data.Models;
using Schedule.Services.Data.Interfaces;
using Schedule.Web.ViewModels.ApplicationUsers;
using Schedule.Web.ViewModels.Consultation;

namespace SchoolShudale.Controllers
{
    public class ConsultationController : BaseController
    {
        private readonly IConsultaionService _consultaionService;
        public ConsultationController(IConsultaionService consultaionService)
        {
            this._consultaionService = consultaionService;
        }
        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            CreateConsultationViewModel consultation = new CreateConsultationViewModel();
            return View(consultation);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateConsultationViewModel viewModel)
        {

            await this._consultaionService.ClearDatabase();
            var info = viewModel;
            await this._consultaionService.RecordInfoInTheDb(info);
            return RedirectToAction(nameof(Schedule));
        }
        [HttpGet]
        public async Task<IActionResult> Schedule()
        {
            // Change the view model
            List<Consultation> consultations = await this._consultaionService.GetAllConsultations();
            Dictionary<string, List<Consultation>> consultationSchedule = await this._consultaionService.ScheduleTheConsultationByDays(consultations);
            return View(consultationSchedule);
        }
        [HttpGet]
        public async Task<IActionResult> Participate(Guid Id)
        {
            Consultation consultation = await this._consultaionService.GetConsultationByIdAsync(Id);
            // Importanted Dublicate check 
            var consultations = await this._consultaionService.GetAllMyConsultationsAsync(this.GetUserId());
            var checkForDoblication = consultations.FirstOrDefault(x => x.Id == consultation.Id);
            if (checkForDoblication != null)
            {
                return RedirectToAction(nameof(Schedule));
            }
            await this._consultaionService.AddConsultataionToTheUser(consultation, this.GetUserId());
            return RedirectToAction(nameof(Mine));

        }
        [HttpGet]
        public async Task<IActionResult> Mine()
        {
            List<Consultation> myConsultations = await this._consultaionService.GetAllMyConsultationsAsync(this.GetUserId());
            return View(myConsultations);
        }
        [HttpGet]
        public async Task<IActionResult> Leave(Guid Id)
        {
            var consultation = await this._consultaionService.GetConsultationByIdAsync(Id);

            await this._consultaionService.RemoveConsultationFromUser(this.GetUserId(), consultation);
            return RedirectToAction(nameof(Mine));
        }
        // Only for the teachers to see the particicpants
        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Details(Guid Id) 
        {
            ApplicationUserViewModel[] usersInConsultation = await this._consultaionService.GetAllParticipantceForAConsultationByIdAsync(Id);
            return View(usersInConsultation);
        }
    }
}

SchoolShudale/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolShudale</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolShudale.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/footer.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolSchedule</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item dropdown">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle text-light" type="button" data-bs-toggle="dropdown">Create</button>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultation" asp-action="Create">Consultations</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Create" asp-action="Teachers">Schedule</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle text-light" type="button" data-bs-toggle="dropdown">Consultation</button>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultation" asp-action="Schedule">Schedule</a>
                                        </li>


                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultation" asp-action="Mine">My Consultation</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Mine" asp-action="Schedule">My Schedule</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SchoolShudale</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>